trigger:
- main

stages:
- stage: Test
  displayName: DataFabric
  
  
  jobs:  
  - job: Test_Login
    displayName: Login
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'fraxses registry login'
      inputs:
        containerRegistry: 'fraxses-registry'
        command: login
    
  - job: Run_Data_Fabric_Image
    dependsOn: ['Test_Login']
    pool:
      vmImage: 'ubuntu-latest'
    container: 
      image: deployment/core:0.1.0-TRAINING
      
    steps:
      - task: Docker@2
        displayName: 'run data fabric image'
        inputs:
          command: run
          arguments: '--rm -v $(Build.SourcesDirectory):/provision deployment/core:0.1.0-TRAINING –sourceDir provision –skipUpload /bin/bash'
           
