trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@2
  displayName: 'fraxses registry login'
  inputs:
    containerRegistry: 'fraxses-registry'
    command: login
    arguments: --username alexb --password Braveshoosiers41
- task: Docker@2
  displayName: 'run data fabric image'
  inputs:
    containerRegistry: 'fraxses-registry'
    command: run
    image: deployment/core:0.1.0-TRAINING
    endpoint: 'fraxses-registry'
    arguments: '--rm -v $(Build.SourcesDirectory):/provision deployment/core:0.1.0-TRAINING –sourceDir provision   –skipUpload /bin/bash'
