trigger:
- main

resources:
  containers:
  - container: data_fabric
      image: deployment/core:0.1.0-TRAINING
      endpoint: 'fraxses-registry'
      options: --user 0:0

stages:
- stage: Test
  displayName: Testing Image
  jobs:  
  - job: Test_Login
    displayName: Login
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'fraxses registry login'
      inputs:
        containerRegistry: 'fraxses-registry'
        command: login
    
  - job: Run_Data_Fabric_Image
    dependsOn: ['Test_Login']
    pool:
      vmImage: 'ubuntu-latest'
    container: data_fabric
    steps:
      - task: Docker@2
        displayName: 'run data fabric image'
        inputs:
          command: run
          arguments: '--rm -v $(Build.SourcesDirectory):/provision deployment/core:0.1.0-TRAINING –sourceDir provision   –skipUpload /bin/bash'
